### ISSUE TITLE
Token request returned http error 400

### ISSUE THREAD

**Issue by Mikeprod** [Azure/azure-data-lake-store-python#185]
### Description
I cannot get a token since yesterday evening (CEST time) and therefore cannot with files stored in any datalake store.
---

### Reproduction Steps
With only the following code : 
```
username = 'myusername'
password = 'mypassword'
tenant_id = 'mytenant'
from azure.datalake.store import core, lib, multithread
token = lib.auth(tenant_id, username, password)
```
I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\username\downloads\azure-data-lake-store-python\azure\datalake\store\lib.py", line 130, in auth
    password, client_id)
  File "C:\Users\username\Anaconda3\lib\site-packages\adal\authentication_context.py", line 145, in acquire_token_with_username_password
    return self._acquire_token(token_func)
  File "C:\Users\username\Anaconda3\lib\site-packages\adal\authentication_context.py", line 109, in _acquire_token
    return token_func(self)
  File "C:\Users\username\Anaconda3\lib\site-packages\adal\authentication_context.py", line 143, in token_func
    return token_request.get_token_with_username_password(username, password)
  File "C:\Users\username\Anaconda3\lib\site-packages\adal\token_request.py", line 286, in get_token_with_username_password
    token = self._get_token_username_password_federated(username, password)
  File "C:\Users\username\Anaconda3\lib\site-packages\adal\token_request.py", line 252, in _get_token_username_password_federated
    username, password)
  File "C:\Users\username\Anaconda3\lib\site-packages\adal\token_request.py", line 212, in _perform_username_password_for_access_token_exchange
    return self._perform_wstrust_assertion_oauth_exchange(wstrust_response)
  File "C:\Users\username\Anaconda3\lib\site-packages\adal\token_request.py", line 192, in _perform_wstrust_assertion_oauth_exchange
    return self._oauth_get_token(oauth_parameters)
  File "C:\Users\username\Anaconda3\lib\site-packages\adal\token_request.py", line 113, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "C:\Users\username\Anaconda3\lib\site-packages\adal\oauth2_client.py", line 281, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS50008: SAML token is invalid. AADSTS50006: The element with ID '_eeff9e30-4011-4389-bdeb-b787a7a3f896' was either unsigned or the signature was invalid.\r\nTrace ID: e8490f62-652e-4792-97b5-d2eb85bd1d00\r\nCorrelation ID: 5e7a1e38-db45-4bfb-880b-74d0859cba31\r\nTimestamp: 2017-08-01 09:56:34Z","error_codes":[70002,50008,50006],"timestamp":"2017-08-01 09:56:34Z","trace_id":"e8490f62-652e-4792-97b5-d2eb85bd1d00","correlation_id":"5e7a1e38-db45-4bfb-880b-74d0859cba31"}

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here: 0.0.14 and same with 0.0.15

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: 64 bit python 3.6.1

**OS Version:** What OS and version are you using?  
Answer here: Windowns 10

**Comment by Mikeprod** [comment]
At this hour this error does not happen anymore.

**Comment by Mikeprod** [comment]
I am having the issue again this morning. Haaaaalp !

**Comment by milanchandna** [comment]
Hi, Apologies for no attention to the thread since long. 
The issue you mentioned is related to authentication problem.
The issue is very old and lot of new versions has been released so hoping you are not facing it still.
In case you are then please re-check your configuration carefully like, username, password and tenant_id.
Read blogs on how to fetch the correct values from Azure portal.
If the config is correct and you are still facing it, please paste the error again so that we can follow up with AzureAD team to check the server logs and find out the problem.
