### ISSUE TITLE
None type has no status code

### ISSUE THREAD

**Issue by A9NAHZZ** [Azure/azure-data-lake-store-python#288]
### Description
Trying to acquire a token, instead got the below error
```
Traceback (most recent call last):
  File "C:\Users\A9NAHZZ\AppData\Local\Programs\Python\Python36\lib\site-packages\graphql\execution\executor.py", line 450, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "C:\Users\A9NAHZZ\AppData\Local\Programs\Python\Python36\lib\site-packages\graphql\execution\executors\sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "main.py", line 12, in resolve_size
    token = lib.auth(settings.tenant, settings.username, settings.password)
  File "C:\Users\A9NAHZZ\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\datalake\store\lib.py", line 150, in auth
    out = get_token_internal()
  File "C:\Users\A9NAHZZ\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\datalake\store\retry.py", line 104, in f_retry
    request_successful = last_exception is None or response.status_code == 401  # 401 = Invalid credentials
AttributeError: 'NoneType' object has no attribute 'status_code'
```

---

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**

### Environment summary
`tok = lib.auth(t, u, p)`
where t, u, p are just strings

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here:
Version: 0.0.45

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
64 3.6

**OS Version:** What OS and version are you using?  
Windows

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Powershell

**Comment by akharit** [comment]
This is a bug and I would fix it in the next release. I'll add a check for none for response.

 However, just to confirm, I am assuming this wouldn't happen very frequently as I response wouldn't be none usually.
