### ISSUE TITLE
Not able to set the ACL - set_acl throws stacktrace

### ISSUE THREAD

**Issue by Gaurang033** [Azure/azure-data-lake-store-python#302]
### Description
I am able to list the ACL on given folder without any issue. However when I am trying to set the permission on any folder. it shows me error. If I try to set `recursive=True` it just hangs. 
I am not sure if I am providing the `acl_spec` correct or not. 
I have tried so far following specs. 

- `acl_spec = "user:Gaurang.Shah@mosaic.com:rwx"`
- `acl_spec = "user:Gaurang.Shah@mosaic.com:r-w-x"`

In both the cases I am getting different errors. 

**Error** for  `acl_spec = "user:Gaurang.Shah@mosaic.com:r-w-x"` :
```Traceback (most recent call last):
  File "/Users/gaurang.shah/PycharmProjects/demo/acl.py", line 21, in <module>
    adl.set_acl(path="tmp/", acl_spec=acl_spec)
  File "/Users/gaurang.shah/Downloads/.venv/lib/python2.7/site-packages/azure/datalake/store/core.py", line 485, in set_acl
    self._acl_call('SETACL', path, acl_spec, invalidate_cache=True)
  File "/Users/gaurang.shah/Downloads/.venv/lib/python2.7/site-packages/azure/datalake/store/core.py", line 459, in _acl_call
    to_return = self.azure.call(action, posix_path, **parms)
  File "/Users/gaurang.shah/Downloads/.venv/lib/python2.7/site-packages/azure/datalake/store/lib.py", line 441, in call
    self.log_response_and_raise(response, PermissionError(path), level=exception_log_level)
  File "/Users/gaurang.shah/Downloads/.venv/lib/python2.7/site-packages/azure/datalake/store/lib.py", line 349, in log_response_and_raise
    raise exception
azure.datalake.store.exceptions.PermissionError: tmp
``` 

**Error** for `acl_spec = "user:Gaurang.Shah@mosaic.com:r-w-x"` 
```
Traceback (most recent call last):
  File "/Users/gaurang.shah/PycharmProjects/demo/acl.py", line 21, in <module>
    adl.set_acl(path="tmp/", acl_spec=acl_spec)
  File "/Users/gaurang.shah/Downloads/.venv/lib/python2.7/site-packages/azure/datalake/store/core.py", line 485, in set_acl
    self._acl_call('SETACL', path, acl_spec, invalidate_cache=True)
  File "/Users/gaurang.shah/Downloads/.venv/lib/python2.7/site-packages/azure/datalake/store/core.py", line 459, in _acl_call
    to_return = self.azure.call(action, posix_path, **parms)
  File "/Users/gaurang.shah/Downloads/.venv/lib/python2.7/site-packages/azure/datalake/store/lib.py", line 454, in call
    self.log_response_and_raise(response, err, level=exception_log_level)
  File "/Users/gaurang.shah/Downloads/.venv/lib/python2.7/site-packages/azure/datalake/store/lib.py", line 349, in log_response_and_raise
    raise exception
azure.datalake.store.exceptions.DatalakeRESTException: Data-lake REST exception: SETACL, tmp
```

---

### Reproduction Steps
```python
acl_spec = "user:Gaurang.Shah@mosaic.com:rwx"
adl.set_acl(path="tmp/", acl_spec=acl_spec)
```

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)

```
Name: azure-datalake-store
Version: 0.0.47
Summary: Azure Data Lake Store Filesystem Client Library for Python
Home-page: https://github.com/Azure/azure-data-lake-store-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /Users/gaurang.shah/Downloads/.venv/lib/python2.7/site-packages
Requires: futures, adal, cffi, azure-nspkg, requests, pathlib2
Required-by: azure
```

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: 64 bit Python 2.7.10

**OS Version:** What OS and version are you using?  
Answer here: MacOS 10.14.6

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash

**Comment by akharit** [comment]
Please use guid for the username Gaurang.Shah@mosaic.com in the aclspec

**Comment by akharit** [comment]
@Gaurang033 Did that fix the error? I'll close this if there isn't any issue
