### ISSUE TITLE
Cancel logic hangs on large folders

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#50]
On a folder containing 100,000 1mb files if I issue a cancel request the operation still hasn't returned control back to me after about 30 minutes (and it appears to still be uploading, very slowly).

**Comment by begoldsm** [comment]
@jbcrail I believe you fixed this right? Can you point to the PR that has reduced this cancel cost for large folders?

**Comment by jbcrail** [comment]
#64 added a shutdown event that every thread looks for. If Ctrl-C is pressed or `ADL[Down|Up]loader.client.shutdown()` is called, then the event is triggered and threads will shutdown at the earliest convenience.

**Comment by rrenfrow86** [comment]
@begoldsm - please confirm this is indeed fixed - PR has been merged.

**Comment by begoldsm** [comment]
@jbcrail it looks like the fix has created a slightly different issue. If a user passes in many cancel requests (for example, hitting ctrl + c a number of times) then the interrupt gets interrupted, resulting in a permanent hang. I was able to reproduce this using the benchmark script that we are using by:
1. run the script and wait ~20 seconds for it to spin up all the threads
2. hit ctrl + c, and continue to do so, making sure you hit it even after the first "interrupt exception" shows up
3. the result should be the following output and no return of control:
[bench_upload_1_50gb] starting...
Traceback (most recent call last):
  File "c:\tools\azure-data-lake-store-python\adlfs\transfer.py", line 423, in m
onitor
    self._wait(poll, timeout)
  File "c:\tools\azure-data-lake-store-python\adlfs\transfer.py", line 409, in _
wait
    time.sleep(poll)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\scripts\benchmarks.py", line 176, in <module>
    bench_upload_1_50gb(adl, lpath_up, rpath, nthreads)
  File "C:\scripts\benchmarks.py", line 16, in wrapped
    result = f(*args, **kwargs)
  File "C:\scripts\benchmarks.py", line 100, in bench_upload_1_50gb
    nthreads=nthreads)
  File "c:\tools\azure-data-lake-store-python\adlfs\multithread.py", line 239, i
n __init__
    self.run()
  File "c:\tools\azure-data-lake-store-python\adlfs\multithread.py", line 277, i
n run
    self.client.run(nthreads, monitor)
  File "c:\tools\azure-data-lake-store-python\adlfs\transfer.py", line 402, in r
un
    self.monitor()
  File "c:\tools\azure-data-lake-store-python\adlfs\transfer.py", line 426, in m
onitor
    self.shutdown()
  File "c:\tools\azure-data-lake-store-python\adlfs\transfer.py", line 418, in s
hutdown
    self._pool.shutdown(wait=True)
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurre
nt\futures\thread.py", line 139, in shutdown
    t.join()
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\threadin
g.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\threadin
g.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by begoldsm** [comment]
@jbcrail note that issuing a single ctrl +c (with no additional ones) does terminate the process rather quickly, its just the case where further ctrl + c calls cause problems.

**Comment by begoldsm** [comment]
This has been resolved and cancel returns in a more reasonable amount of time, although cancelling a very large folder upload (50K 1mb files) will still take some time to return control.
