### ISSUE TITLE
Upload 100GB file on machine with 112GB of memory results in OOM error and cascading errors

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#56]
When I attempt to upload a 100GB file with 128 threads on a vm with 112GB of memory I get an out of memory error, followed by a large number of IO errors on closed streams. 

When an error is encountered it should not immediately result in cascading errors if possible, and retry should be considered (although with OOM errors that is probably not practical). 

Below is a partial stack trace. The IO errors continue for a long time:

PS E:\ingress> python C:\tools\sampleUploadDownload.py
Uploading file...
Traceback (most recent call last):
  File "C:\tools\sampleUploadDownload.py", line 24, in <module>
    multithread.ADLUploader(adl, lpath=fileLocationToUpload, rpath=remoteFolderName + '/' + remoteFileName, nthreads=128
) # change the thread number up or down depending on tuning for perf
MemoryError
Exception ignored in: <bound method AzureDLFile.__del__ of <ADL file: /tmp/e683991075_35701915648>>
Traceback (most recent call last):
  File "c:\tools\azure-data-lake-store-python\adlfs\core.py", line 702, in __del__
    self.close()
  File "c:\tools\azure-data-lake-store-python\adlfs\core.py", line 685, in close
    self.flush(force=True)
  File "c:\tools\azure-data-lake-store-python\adlfs\core.py", line 628, in flush
    if self.buffer.tell() == 0:
ValueError: I/O operation on closed file.
Exception ignored in: <bound method AzureDLFile.__del__ of <ADL file: /tmp/e683991075_42949672960>>
Traceback (most recent call last):
  File "c:\tools\azure-data-lake-store-python\adlfs\core.py", line 702, in __del__
    self.close()
  File "c:\tools\azure-data-lake-store-python\adlfs\core.py", line 685, in close
    self.flush(force=True)
  File "c:\tools\azure-data-lake-store-python\adlfs\core.py", line 628, in flush
    if self.buffer.tell() == 0:
ValueError: I/O operation on closed file.

**Comment by begoldsm** [comment]
This issue is resolved by one of the following:
1. using <= 12 threads.
2. using the 64bit version of python (which can scale threads until you are actually out of memory).
