### ISSUE TITLE
Pri 0: Uploading 50,000 1mb files resulting in a memory exception

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#69]
The following exception is thrown when attempting to upload 50,000 1MB files. Note that it keeps going on like this for a very long time:

Uploading 50000 1MB files...
Traceback (most recent call last):
  File "C:\tools\sampleUploadDownload.py", line 36, in <module>
    multithread.ADLUploader(adl, lpath='D:\\ingress\\largeFolder', rpath=remoteFolderName + '/50000files', nthreads=64)
# change the thread number up or down depending on tuning for perf
  File "c:\tools\azure-data-lake-store-python\adlfs\multithread.py", line 233, in __init__
    self.run()
  File "c:\tools\azure-data-lake-store-python\adlfs\multithread.py", line 271, in run
    self.client.run(nthreads, monitor)
  File "c:\tools\azure-data-lake-store-python\adlfs\transfer.py", line 337, in run
    self.monitor()
  File "c:\tools\azure-data-lake-store-python\adlfs\transfer.py", line 370, in monitor
    self._wait(poll, timeout)
  File "c:\tools\azure-data-lake-store-python\adlfs\transfer.py", line 352, in _wait
    self._update()
  File "c:\tools\azure-data-lake-store-python\adlfs\transfer.py", line 326, in _update
    self.save()
  File "c:\tools\azure-data-lake-store-python\adlfs\transfer.py", line 410, in save
    pickle.dump(all_downloads, f)
MemoryError
Unhandled exception in thread started by
Unhandled exception in thread started by Unhandled exception in thread started by

Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-173, started daemon 11736)>>
Traceback (most recent call last):
Unhandled exception in thread started by
Unhandled exception in thread started by Unhandled exception in thread started by
Exception ignored in: <generator object CaseInsensitiveDict.__iter__.<locals>.<genexpr> at 0x37CD71D8>
Traceback (most recent call last):
Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-149, started daemon 17448)>>
Traceback (most recent call last):
Traceback (most recent call last):
Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-167, started daemon 4856)>>
Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-135, started daemon 18448)>>
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 66, in _work
er
Traceback (most recent call last):
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 66, in _work
er
Traceback (most recent call last):
Traceback (most recent call last):
<bound method Thread._bootstrap of <Thread(Thread-155, started daemon 6328)>>
Exception in thread Thread-189:
Traceback (most recent call last):
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 64, in _work
er
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 862, in run
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 81, in _work
er
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\logging\__init__.py", line 1326, in critical
MemoryError

  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 66, in _work
er
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 64, in _work
er
Traceback (most recent call last):
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 64, in _work
er
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 66, in _work
er
Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-160, started daemon 17808)>>
Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-174, started daemon 14356)>>
MemoryError
MemoryError:
MemoryError

During handling of the above exception, another exception occurred:

  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 64, in _work
er
Traceback (most recent call last):
Exception ignored in: <bound method AzureDLFile.__del__ of <ADL file: /begoldsm/50000files/f1/f2/16926>>
Traceback (most recent call last):
    work_item.run()
  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 66, in _work
er
Exception ignored in: <bound method AzureDLFile.__del__ of <ADL file: /begoldsm/50000files/f1/11838>>
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

  File "C:\Users\adlsperf\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 64, in _work
er
MemoryError

**Comment by begoldsm** [comment]
This is resolved through the use of python x64 or reducing the thread count on 32bit python.
